spring.application.name=spring

spring.datasource.url=jdbc:postgresql://postgres:5432/quest_board
spring.datasource.username=quest_user
spring.datasource.password=quest_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always