spring.application.name=spring

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=quest_user
spring.datasource.password=quest_pass

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always